[package]
name = "mqttwrk"
version = "0.1.0"
authors = ["tekjar <raviteja@bytebeam.io>"]
edition = "2018"


[dependencies]
rumq-client = "0.1.0-alpha.10"
tokio = { version = "0.2", features = ["full"] }
pretty_env_logger = "0.4"
rand = "0.7"
argh = "0.1"
